### PR TITLE
[#12] Buffered s3 index input & S3 Block Cache

### PR DESCRIPTION
**Pull request by adamyy**
* Implement `S3IndexInput` with S3 range GET and Buffer input (mimicked the implementation of `SimpleFSIndexInput`)
* Solve the issue mentioned in #12 by reading in file content in chunks of 64 MB (which is a number picked arbitrarily with the hope that it would balance between memory usage and the number of GETs, might need to be tuned)
* However, undo'ed a lot of the caching mechanism, and caching might need to be reconsidered separately

### CODE REVIEW

**Comment by adamyy** [comment]
Here is a sample run of CORD19 abstract index: https://gist.github.com/adamyy/6944ab8f31a656916b763b6e12eb1652

Perhaps the most interesting log is `readingFromS3`, "offset" is the location at which the file is being read, and "length" is the number of bytes being read.

**Comment by adamyy** [comment]
I implemented a file block cache with LRU eviction strategy, the file blocks are aligned with fixed 64 MB in size (except when the file size is < 64 MB) in order to increase the cache hit rate. 

Here is a sample run for `lucene-index-cord19-abstract-2020-07-16` (~2.7GB, with **stored** fields): [S3BlockCache logs](https://gist.github.com/adamyy/caa49fd894d14791675704e304182bd4), [full logs](https://gist.github.com/adamyy/c5abc33048b997e73b4a3704ee120e74).

From the logs, it seems like the block cache serve its purpose decently well: for small files such as `_0_Lucene50_0.tip`, the cache can keep it in memory and avoid repeated GET from S3. For large files such as `_0.fdt` (~2.4GB), because we can only fit so much in Lambda's memory, the reading was basically doing a full scan (which does not benefit from caching much). 

Comparing with the previous non-cached version, the new implementation shed the number of GETs by about half (~80 > ~40), and 18 GETs were attributed to the scan of `_0.fdt`. There were also a few duplicated GET for some small files likely caused by the IndexInput clones (the thundering herd problem). Overall, the memory usage was kept under 2700 MB, this is tuneable by lowering the `MAX_HEAP_SIZE` in `S3BlockCache`.

Right now each request made against this large index is still very time consuming due to the scan, but I think using a "thin" index with no **stored** fields and applying document partitioning should be the solution to that problem. Meanwhile, this PR resolves the issue mentioned in #8 and #12.

@lintool Can I please get some 👀?

**Comment by adamyy** [comment]
Note to self: change `LOG.info` to `LOG.trace` to keep logs free of debugging info

**Comment by adamyy** [comment]
@lintool I tested on `msmarco-passage` index without positions, contents or raw. The size of the index is ~2.1G.

Overall, the first call (cold start) takes around ~1 minute to finish, subsequent calls usually finish <1 second and there are basically no cache misses because the majority of the index fits in the memory. Maximum memory usage was around 2800MB which is >90% of the quota, but I didn't experience OOMs in my tests. 

image

**Comment by lintool** [comment]
Off the top of my head, this is similar to the behavior of my original naive implementation of reading in the entire index at cold start time.

If we are paging in blocks of the index 64 MB at a time, shouldn't cold start time be reduced? That is, unless we need all (most) the blocks to even serve the first query?

For MS MARCO doc, can you build a stripped down (minimum) index and tell me the size?

**Comment by adamyy** [comment]
@lintool The current implementation actually downloads in 256 MB chunks, and it caches the downloaded content in 64 MB chunks for finer grained eviction. My rationale for this eager download behavior is that it helps reduce the total number of GETs from S3 (GET costs $0.0005 per request).

I experimented with MS MARCO doc, the minimal index is ~10.7 GB. And I profiled some search requests to see how much data is read from S3 and how much is actually read by the program. To my surprises, it seems like Lucene only needs to read ~200 to ~300 MB to execute a search query, even when I set `max_docs` to 100. However, the current eager download behavior tends to read a lot more data from S3 (>2GB), so I think I can tune it down to speed up cold start. 

Another unfortunate discovery I had is that there are some bugs with the `S3CachedReader` or `S3IndexInput`, as I get unexpected exception from searching certain terms on MS MARCO doc. I am currently in the process of isolating the issue and hopefully I will have it resolved in this week.

**Comment by adamyy** [comment]
@lintool I fixed the aforementioned issue, it was a boundary case in `S3FileBlock.of`. I also removed the eager download behavior and I observed slight improvement (<50s) on cold start when I was testing with `msmarco-passage`.

image

**Review by lintool — APPROVED** [review]
LG!

Appreciate the test case.

I'd like to `.*` imports but not a big deal.

Go ahead and merge when ready - please write a good commit msg.

**Pull request merged**
